import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext({ viewport: { width: 1280, height: 1000 } })).newPage()
p.on('pageerror', e => console.log('PAGEERROR:', e.message.slice(0,160)))
await p.goto('http://127.0.0.1:5199/#/sources', { waitUntil: 'networkidle' })
await p.waitForTimeout(2000)
const g = p.getByText('Cris Test 2: existing project')
if (await g.count()) { await g.click(); await p.waitForTimeout(2500) }
await p.goto('http://127.0.0.1:5199/#/sources', { waitUntil: 'networkidle' })
await p.waitForTimeout(2500)
await p.getByRole('button', { name: /add a source/i }).click()
await p.waitForTimeout(600)
await p.getByRole('button', { name: /a folder on this machine/i }).click()
await p.waitForTimeout(2500)
await p.getByRole('option', { name: /KAE-Ecosystem/ }).first().click()
await p.waitForTimeout(3000)
await p.screenshot({ path: '/tmp/shots/picked.png', fullPage: true })
console.log('ok')
await b.close()
