import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await (await browser.newContext({ viewport: { width: 1280, height: 1000 } })).newPage()
await page.goto('http://127.0.0.1:5199/#/dashboard', { waitUntil: 'networkidle' })
await page.waitForTimeout(1500)
await page.getByText('Cris Test 2: existing project').click()
await page.waitForTimeout(2500)
await page.goto('http://127.0.0.1:5199/#/sources', { waitUntil: 'networkidle' })
await page.waitForTimeout(3000)
await page.getByRole('button', { name: /add a source/i }).click()
await page.waitForTimeout(600)
await page.getByRole('button', { name: /clone a repository here first/i }).click()
await page.waitForTimeout(600)
await page.screenshot({ path: '/tmp/shots/sources.png', fullPage: true })
await browser.close()
