import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await (await b.newContext({ viewport: { width: 1280, height: 1100 } })).newPage()
p.on('pageerror', e => console.log('PAGEERROR:', e.message.slice(0,180)))
await p.goto('http://127.0.0.1:5199/#/setup', { waitUntil: 'networkidle' })
await p.waitForTimeout(2000)
const pick = p.getByText('Cris Test 2: existing project')
if (await pick.count()) { await pick.click(); await p.waitForTimeout(2500) }
await p.goto('http://127.0.0.1:5199/#/setup', { waitUntil: 'networkidle' })
await p.waitForTimeout(3000)
await p.evaluate(() => window.scrollTo(0, 900))
await p.waitForTimeout(500)
await p.screenshot({ path: '/tmp/shots/dest.png' })
console.log('ok')
await b.close()
